name: "Unit Test"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run docker test
      run: |
        docker build . --no-cache -f Dockerfile.test -t axolotl-test